// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATw15PaNYvu8BRQhdim1Px2hrGqaHiwIw',
    appId: '1:341161446747:web:17adc2aa0131bb80d69e7e',
    messagingSenderId: '341161446747',
    projectId: 'freshnearby-17349',
    authDomain: 'freshnearby-17349.firebaseapp.com',
    storageBucket: 'freshnearby-17349.firebasestorage.app',
    measurementId: 'G-6ZNBSH3W19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98AuBs6eU9q9TE8sxX1vCh9gvhKnA1gg',
    appId: '1:341161446747:android:f296fd6934d9f9d6d69e7e',
    messagingSenderId: '341161446747',
    projectId: 'freshnearby-17349',
    storageBucket: 'freshnearby-17349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhaFIveGzA2E7erNZB-4LbEXkOSBM2i4M',
    appId: '1:341161446747:ios:cf213424db078da3d69e7e',
    messagingSenderId: '341161446747',
    projectId: 'freshnearby-17349',
    storageBucket: 'freshnearby-17349.firebasestorage.app',
    iosBundleId: 'com.frshnearby.app',
  );
}
